### ISSUE TITLE
Design: Why not build this directly into cron?

### ISSUE THREAD

**Issue by luisgerhorst** [abel-vs/carbon-scheduler#15]
I was just wondering whether you considered building this directly into cron instead of creating it as a tool that used cron/at as tools. Any insights are welcome :)

**Comment by wandersiemers** [comment]
Hi! Mostly because we're a bit more familiar with writing Python than C. However, if you are, I think an approach like you propose would be great too. 

Note this is a university course project and we're not actively maintaining it, by the way. Educational purposes only :)
